My portfolio Microverse project pull request
Atril33/My_Portfolio pull request #1
Opened 2023-01-13 15:07 UTC by Atril33

2023-01-13 18:19 UTC, bienvenuushindi requested changes
### Hi @Atril33 ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔
- Nice Design. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-13 18:19 UTC, bienvenuushindi commented on index.html
> + </div>
:red_circle: Kindly replace this parent div tag with a nav tag or you can wrap this block in a nav tag container. The nav tag is for semantics reason, and the right position for convention and user experience for mobile devices.

2023-01-13 18:19 UTC, bienvenuushindi commented on index.html
> +</div>
:red_circle: Please make sure you wrap everything here in a container. This container should be  a `section` tag. A section tag represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

```
<section>
     <!---Please Add your code here-->
</section>
```

2023-01-13 18:19 UTC, bienvenuushindi commented on index.html
> +<img src="Images/background_img.png" alt="Background Image">
:red_circle: I think it will be better if this  background is set using CSS background-image property.  If an image is not part of the content (aesthetic reasons) use CSS background-image. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info. 
If the image is part of the content such as a logo or diagram or person (real person, not stock photo people) then use the <img /> tag plus alt attribute. For everything else there's CSS background images

2023-01-13 18:19 UTC, bienvenuushindi commented on style.css
> +@import url("https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200&display=swap");
:red_circle: Kindly make sure you import the right google font to match the Figma Design. The figma template uses `font-family: 'Poppins';`  

|Your Design|Figma Design|
|:--------------:|:------------------:|
|![family](https://user-images.githubusercontent.com/26736582/212389151-9bf4bf2d-1bca-4512-9373-8ea6da53482e.png)|![font-family](https://user-images.githubusercontent.com/26736582/212389191-43d13324-be94-43de-a63b-4ded6af1415b.png)|

2023-01-13 18:19 UTC, bienvenuushindi commented on index.html
> +    <h3><a href="#">LET’S CONNECT</a></h3>
:red_circle: Please make sure you remove the underline applied on  this text. 
You can add this code to your style.css to override the default value.
```
a {
  text-decoration: none
} 
``` 
|Your Design|Figma Design|
|:--------------:|:------------------:|
|![your desi](https://user-images.githubusercontent.com/26736582/212391203-91c05aa8-bb54-4f61-a1c6-66b839d3241b.png)|![figmaa](https://user-images.githubusercontent.com/26736582/212391320-491b6d18-7913-41fd-adc3-5aebac95123b.png)|

2023-01-14 08:25 UTC, binhussen approved these changes
Hi @Atril33 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 08:25 UTC, binhussen commented on README.md
> +    <img src="https://github.com/didierganthier/hello-microverse-cr-review/blob/master/murple_logo.png" alt="logo" width="150px" />
- [Optional] Kindly remove the microverse logo and replace with yours if you have otherwise live it empty 👌👍

2023-01-14 08:25 UTC, binhussen commented on style.css
> +  color: #000;
- [Optional] kindly, use the Figma text color, for your heading which is `color: #172B4D;` o fit the Figma design👍👌.

2023-01-14 08:25 UTC, binhussen commented on index.html
> +        Glad to see you!</h2>
- [Optional] Kindly, this part is your main heading so use an `h1` tag for search engines. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info. 👍👌

2023-01-14 08:25 UTC, binhussen commented on index.html
> +    <h3><a href="#">LET’S CONNECT</a></h3>
- kindly, you are using the default `a` text color, please use `color: #7F8CFF;
`  to fit the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=NVsQsZj0ugMKgNNU-0).👌👌

2023-05-24 13:37 UTC, merged